{% set name = "anyscale" %}
{% set version = "0.24.87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/17/ba/a03dbcfa3fc900611d2b56c52cd874d0db708d811c58aab5b5d784789b35/anyscale-{{ version }}.tar.gz
  sha256: bbad393c4e9fde2fb669561aa0efac77309618a3f8716989c723a412b56608fb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - anyscale = anyscale.scripts:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - aiohttp >=3.7.4
    - argon2-cffi
    - boto3 >=1.26.76
    - botocore >=1.19.52
    - certifi >=2023.7.22
    - click >=7.0
    - colorama
    - gitpython
    - google-auth
    - halo
    - humanize
    - jsonpatch
    - jsonschema
    - oauth2client
    - packaging
    - pathspec >=0.8.1
    - python-dateutil
    - pyyaml
    - requests
    - rich
    - six >=1.10
    - smart_open
    - tabulate
    - tqdm
    - tzlocal
    - urllib3 >=1.26.17
    - wrapt

test:
  imports:
    - anyscale
  requires:
    - python {{ python_min }}
    # until https://github.com/pypa/pip/issues/12884 is fixed
    - pip <24.2
  commands:
    - pip check
    - anyscale --version

about:
  home: https://docs.anyscale.com/reference/cli
  summary: Command Line Interface for Anyscale
  description: Command Line Interface for Anyscale
  license: LicenseRef-AS
  license_file: LICENSE
  doc_url: https://docs.anyscale.com/reference/cli

extra:
  recipe-maintainers:
    - timkpaine
