{% set name = "anyscale" %}
{% set version = "0.26.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anyscale-{{ version }}.tar.gz
  sha256: e2b82770927ecfd5d8897d26d82018c6d0f8b4a7328b38dc0212c2bd2a4f6c3c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - anyscale = anyscale.scripts:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - boto3 >=1.26.76
    - botocore >=1.19.52
    - aiohttp >=3.7.4
    - certifi >=2024.8.30
    - click >=7.0
    - colorama
    - gitpython
    - google-auth
    - jsonpatch
    - jsonschema
    - oauth2client
    - packaging
    - pathspec >=0.8.1
    - python-dateutil
    - requests
    - rich
    - six >=1.10
    - tabulate
    - urllib3 >=1.26.17
    - wrapt
    - pyyaml
    - smart_open
    - tqdm
    - tzlocal
    - humanize
    - typing_extensions
    - halo
    - log_symbols >=0.0.14
    - spinners >=0.0.24
    - termcolor >=1.1.0
    - colorama >=0.3.9
    # - argon2-cffi
    # - tabulate

test:
  imports:
    - anyscale
  requires:
    - python {{ python_min }}
    # until https://github.com/pypa/pip/issues/12884 is fixed
    - pip <24.2
  commands:
    - pip check
    - anyscale --version

about:
  home: https://docs.anyscale.com/reference/cli
  summary: Command Line Interface for Anyscale
  description: Command Line Interface for Anyscale
  license: LicenseRef-AS
  license_file: LICENSE
  doc_url: https://docs.anyscale.com/reference/cli

extra:
  recipe-maintainers:
    - timkpaine
