{% set name = "anyscale" %}
{% set version = "0.24.71" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61c4e98dad2e132748749557a947ca935f7a7283778ed8e4cb40822be71fdd49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - anyscale = anyscale.scripts:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - aiohttp >=3.7.4
    - argon2-cffi
    - boto3 >=1.26.76
    - botocore >=1.19.52
    - certifi >=2023.7.22
    - click >=7.0
    - colorama
    - gitpython
    - google-auth
    - halo
    - humanize
    - jsonpatch
    - jsonschema
    - oauth2client
    - packaging
    - pathspec >=0.8.1
    - python-dateutil
    - pyyaml
    - requests
    - rich
    - six >=1.10
    - smart_open
    - tabulate
    - tqdm
    - tzlocal
    - urllib3 >=1.26.17
    - wrapt

test:
  imports:
    - anyscale
  requires:
    # until https://github.com/pypa/pip/issues/12884 is fixed
    - pip <24.2
  commands:
    - pip check
    - anyscale --version

about:
  home: https://docs.anyscale.com/reference/cli
  summary: Command Line Interface for Anyscale
  description: Command Line Interface for Anyscale
  license: LicenseRef-AS
  license_file: LICENSE
  doc_url: https://docs.anyscale.com/reference/cli

extra:
  recipe-maintainers:
    - timkpaine
